# Generated by Django 5.0.4 on 2024-05-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSharing',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
