# Generated by Django 5.0.4 on 2024-05-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesharing',
            old_name='doctor',
            new_name='reciever_doctor',
        ),
        migrations.RenameField(
            model_name='messagesharing',
            old_name='patient',
            new_name='sender_doctor',
        ),
    ]
