# Generated by Django 5.0.4 on 2024-05-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesharing', '0002_rename_doctor_messagesharing_reciever_doctor_and_more'),
        ('user', '0002_admin_is_active_doctor_is_active_patient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesharing',
            name='reciever_doctor',
        ),
        migrations.AddField(
            model_name='messagesharing',
            name='receiver_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user.doctor'),
        ),
        migrations.AlterField(
            model_name='messagesharing',
            name='sender_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user.doctor'),
        ),
    ]
